### ISSUE TITLE
Going beyond context [ thought dump ]

### ISSUE THREAD

**Issue by ainsleymcgrath** [ainsleymcgrath/nothing#10]
At the time of writing, the only interactivity beyond _"Press enter to continue..."_ is the collection of `context` before the run of a task. 

This concept comes directly from [the word of our prophet](https://blog.danslimmon.com/2019/07/15/do-nothing-scripting-the-key-to-gradual-automation/). I want no expansion of that feature as an homage and in the interest of building our whimsical home on a foundation of austerity.

Naturally, though, there is a great temptation to soup this up. Boolean logic, arbitrary Python expressions, derived values. The sky is the freaking limit!

However, we literally have a "dogma" issue label. How meta.

This (non-functional) sketch of a (pretty stupid and contrived) Task Spec includes a `presets` key.

```yaml
---
title: Prepare for a presentation

# the key is the variable, the value is how it's asked for
context: 
  - name: What's your name?
  - presentation_topic: What's the topic of your presentation?
  - nervous: Are you feeling nervous about it? (y/n)

# presets are compiled after context, but before steps
presets:
  - calm_down: Take a quick walk, {name}.
  - confidence_booster: Give yourself a pat on the back, {name}!
  
steps: |-
  { calm_down if nervous else confidence_booster }
    
  Make bullets for major points if you haven't.
  
  Find someone to read your notes to. They don't even have to really listen!
  
  Go slow! The longest pause you can muster is still not long enough to be weird.
```

The idea here was to explore the idea of pre-cooking longer strings and providing a convenient way to conditionally include them. Could even be cool to short circuit and completely omit stuff in certain situations, say a step had `{[PRESET] or None}` and was able to short-circuit content out of existence as needed. Fun!

I think perhaps all such considerations should be tabled until further notice EXCEPT, perhaps, a revisiting of the `preset` concept.

What if presets were like context variables that were set at write time? And a redundantly named context variable could be used to optionally override? Or perhaps, when `presets` are present, the user can be asked after context collection whether or not they'd like to override any of them?

Now _there's_ a feature. Slimmon's original do-nothing script includes hard-coded values in the source. I'm sure there will be a great temptation to do this in specs as well. Let's get ahead of it?

```python
class WaitForBuildStep(object):
    build_url = "http://example.com/builds/user_keys"
    def run(self, context):
        print("Wait for the build job at {0} to finish".format(self.build_url))
        wait_for_enter()
```

As a moonshot implementation, just cuz we are here, perhaps it'd be craziest of all to accept environment variables as presets? This way, private information (such as the `build_url` above) could be kept private in the (likely) event that someone would want their `.nothing` in VC.
